def generate_readme(result: Dict) -> str:
    """Generate production-ready README.md."""
    return f"""# {os.path.basename(result['project_path'])}

## 🏗️ Architecture Overview
{result['project_summary'][:500]}...

## 🚪 Entry Points
{chr(10).join([f"- `{ep}`" for ep in result['workflow']['entrypoints']])}

## 📊 Modules by Importance
{chr(10).join([f"- `{m[0]}` ({m[1]:.0%})" for m in result['workflow']['top_modules']])}

## 🛡️ Security Status
{len(result['security']['risks'])} risks detected

---
*Generated by Codebase Workflow Summarizer*"""
